import Link from 'next/link';
import { ArrowRight, BarChart3, Check, CircleDollarSign, ShieldCheck, Sparkles, TrendingUp, Zap } from 'lucide-react';

const examples = [
  ['🎮', 'Gaming', 'Nintendo Switch OLED', '£185'],
  ['📱', 'Electronics', 'iPhone 14 128GB', '£315'],
  ['👟', 'Fashion', 'Nike Dunk Low', '£72'],
];

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><Link href="/" className="logo">Worth<span>It</span></Link><div className="landing-nav-right"><span className="nav-pill"><Zap size={14}/> UK resale + trade-in</span><Link href="/check" className="nav-cta">Check an item <ArrowRight size={15}/></Link></div></nav>
    <section className="landing-hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="eyebrow"><Sparkles size={14}/> The smarter way to sell second-hand</div><h1>Know what it’s worth.<br/><em>Then choose what to do.</em></h1><p>Get a realistic UK resale value, compare it with a trade-in, and decide whether to sell it yourself or take the easy route.</p><div className="hero-actions"><Link href="/check" className="primary-hero">Check what it’s worth <ArrowRight size={18}/></Link><a href="#how" className="secondary-hero">See how it works</a></div><div className="hero-proof"><span><Check size={14}/> Free to use</span><span><Check size={14}/> No account needed</span><span><Check size={14}/> UK-focused</span></div></section>
    <section className="value-strip"><div><b>01</b><span>Identify</span><small>Photo or description</small></div><ArrowRight/><div><b>02</b><span>Value</span><small>Realistic resale range</small></div><ArrowRight/><div><b>03</b><span>Choose</span><small>Sell or trade it in</small></div></section>
    <section className="landing-section" id="how"><div className="section-kicker">ONE CHECK. TWO ROUTES.</div><div className="split-heading"><h2>Get the number first.<br/><span>Make the decision second.</span></h2><p>WorthIt is built around the bit that matters: knowing what your item is actually worth before you hand it over or list it.</p></div><div className="route-cards"><div className="route-card dark"><div className="route-icon"><TrendingUp/></div><small>MAXIMUM RETURN</small><h3>Sell it yourself</h3><p>See a realistic selling range and where your item could fit across the UK resale market.</p><div className="route-bottom"><b>Potentially more money</b><ArrowRight/></div></div><div className="route-card light"><div className="route-icon"><ShieldCheck/></div><small>MINIMUM HASSLE</small><h3>Trade it in</h3><p>Compare the convenience of a trade-in with your estimated private-sale value.</p><div className="route-bottom"><b>Less effort, quicker exit</b><ArrowRight/></div></div></div></section>
    <section className="landing-section examples-section"><div className="section-kicker">SEE IT IN ACTION</div><div className="split-heading"><h2>From old tech to<br/><span>trainers and consoles.</span></h2><p>A few examples of the kind of everyday items WorthIt is designed to value.</p></div><div className="landing-examples">{examples.map(([icon,cat,name,price]) => <Link href={`/check?item=${encodeURIComponent(name)}`} className="landing-example" key={name}><span className="landing-example-icon">{icon}</span><div><small>{cat}</small><b>{name}</b></div><strong>{price}</strong><ArrowRight size={17}/></Link>)}</div></section>
    <section className="numbers-band"><div><CircleDollarSign/><b>Resale + trade-in</b><span>in one simple flow</span></div><div><BarChart3/><b>Market-aware</b><span>ranges, not fake precision</span></div><div><Sparkles/><b>Built for sellers</b><span>from first check to listing</span></div></section>
    <section className="final-cta"><div className="eyebrow"><Sparkles size={14}/> Ready?</div><h2>Let’s find out what<br/>your stuff is worth.</h2><Link href="/check" className="primary-hero">Start a valuation <ArrowRight size={18}/></Link></section><footer className="landing-footer">WorthIt · UK resale estimates · Indicative values, not guaranteed offers.</footer>
  </main>;
}
